function AMB_A = Amat_AMB(in1,in2,g,in4,in5)
%AMAT_AMB
%    AMB_A = AMAT_AMB(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Sep-2018 01:22:29

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
th1 = in4(:,1);
th2 = in4(:,2);
th3 = in4(:,3);
t2 = th1-th2;
t3 = cos(t2);
t4 = sin(th2);
t5 = cos(th2);
t6 = sin(th1);
t7 = L1.*t6;
t8 = cos(th1);
t9 = L1.*t8;
t10 = sin(th3);
t11 = L2.*t4;
t12 = L3.*t10.*(1.0./2.0);
t13 = t7+t11+t12;
t14 = cos(th3);
t15 = L2.*t5;
t16 = L3.*t14.*(1.0./2.0);
t17 = t9+t15+t16;
t18 = th1-th3;
t19 = cos(t18);
t20 = L2.^2;
t21 = th2-th3;
t22 = cos(t21);
t23 = L2.*t22.*6.0;
t24 = L3.*4.0;
AMB_A = reshape([L1.*(L1.*m1.*2.0+L1.*m2.*6.0+L1.*m3.*6.0+L2.*m2.*t3.*3.0+L2.*m3.*t3.*6.0+L3.*m3.*t19.*3.0).*-2.0,L1.*L2.*m2.*t3.*-6.0-L1.*L2.*m3.*t3.*1.2e1-L1.*L3.*m3.*t19.*6.0,L1.*t19.*6.0,-m2.*t20-L2.*m3.*t4.*t13.*1.2e1-L2.*m3.*t5.*t17.*1.2e1-L2.*m2.*t4.*(t7+L2.*t4.*(1.0./2.0)).*6.0-L2.*m2.*t5.*(t9+L2.*t5.*(1.0./2.0)).*6.0,m2.*t20.*-4.0-m3.*t20.*1.2e1-L2.*L3.*m3.*t22.*6.0,t23,-L3.^2.*m3-L3.*m3.*t10.*t13.*6.0-L3.*m3.*t14.*t17.*6.0,-L3.*m3.*(t23+t24),t24],[3,3]);
