function LAG_A = Amat_LAG_5_link(in1,in2,in3)
%AMAT_LAG_5_LINK
%    LAG_A = AMAT_LAG_5_LINK(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Dec-2017 00:44:18

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
L4 = in1(:,4);
L5 = in1(:,5);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
m4 = in2(:,4);
m5 = in2(:,5);
th1 = in3(:,1);
th2 = in3(:,2);
th3 = in3(:,3);
th4 = in3(:,4);
th5 = in3(:,5);
t2 = m4.*2.0;
t3 = m5.*2.0;
t4 = th1-th2;
t5 = cos(t4);
t6 = m3.*2.0;
t7 = m2+t2+t3+t6;
t8 = m3.*3.0;
t9 = m4.*3.0;
t10 = m5.*3.0;
t11 = m3+t2+t3;
t12 = m4+t3;
t13 = th1-th3;
t14 = cos(t13);
t15 = th2-th3;
t16 = cos(t15);
t17 = th1-th4;
t18 = cos(t17);
t19 = th2-th4;
t20 = cos(t19);
t21 = th3-th4;
t22 = cos(t21);
t23 = th1-th5;
t24 = cos(t23);
t25 = th2-th5;
t26 = cos(t25);
t27 = th3-th5;
t28 = cos(t27);
t29 = th4-th5;
t30 = cos(t29);
LAG_A = reshape([L1.^2.*(m1+m2.*3.0+t8+t9+t10).*(2.0./3.0),L1.*t5.*t7.*3.0,L1.*t11.*t14.*3.0,L1.*t12.*t18.*3.0,L1.*t24.*-3.0,L1.*L2.*t5.*t7,L2.*(m2+t8+t9+t10).*2.0,L2.*t11.*t16.*3.0,L2.*t12.*t20.*3.0,L2.*t26.*-3.0,L1.*L3.*t11.*t14,L3.*t11.*t16.*3.0,L3.*(m3+t9+t10).*2.0,L3.*t12.*t22.*3.0,L3.*t28.*-3.0,L1.*L4.*t12.*t18,L4.*t12.*t20.*3.0,L4.*t12.*t22.*3.0,L4.*(m4+t10).*2.0,L4.*t30.*-3.0,L1.*L5.*m5.*t24,L5.*m5.*t26.*3.0,L5.*m5.*t28.*3.0,L5.*m5.*t30.*3.0,L5.*-2.0],[5,5]);
