function LAG_A = Amat_LAG_2_link(in1,in2,in3)
%AMAT_LAG_2_LINK
%    LAG_A = AMAT_LAG_2_LINK(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Dec-2017 00:43:18

L1 = in1(:,1);
L2 = in1(:,2);
m1 = in2(:,1);
m2 = in2(:,2);
th1 = in3(:,1);
th2 = in3(:,2);
t2 = th1-th2;
t3 = cos(t2);
LAG_A = reshape([L1.*(m1+m2.*3.0).*2.0,L1.*t3.*-3.0,L2.*m2.*t3.*3.0,L2.*-2.0],[2,2]);
