function AMB_b = bvec_AMB(in1,in2,g,in4,in5)
%BVEC_AMB
%    AMB_B = BVEC_AMB(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Sep-2018 01:22:29

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
th1 = in4(:,1);
th2 = in4(:,2);
th3 = in4(:,3);
thD1 = in5(:,1);
thD2 = in5(:,2);
thD3 = in5(:,3);
t2 = thD1.^2;
t3 = sin(th1);
t4 = thD2.^2;
t5 = sin(th2);
t6 = thD3.^2;
t7 = sin(th3);
t8 = cos(th1);
t9 = cos(th2);
t10 = cos(th3);
t11 = L1.*t3;
t12 = L2.*t5;
t13 = L3.*t7.*(1.0./2.0);
t14 = t11+t12+t13;
t15 = L1.*t2.*t8;
t16 = L1.*t2.*t3;
t17 = L1.*t8;
t18 = th1-th2;
t19 = sin(t18);
t20 = th2-th3;
t21 = sin(t20);
t22 = th1-th3;
t23 = sin(t22);
AMB_b = [m2.*(t15+L2.*t4.*t9.*(1.0./2.0)).*(t11+L2.*t5.*(1.0./2.0)).*1.2e1-m2.*(t16+L2.*t4.*t5.*(1.0./2.0)).*(t17+L2.*t9.*(1.0./2.0)).*1.2e1+g.*m2.*(t12+L1.*t3.*2.0).*6.0+m3.*t14.*(t15+L2.*t4.*t9+L3.*t6.*t10.*(1.0./2.0)).*1.2e1+g.*m3.*t14.*1.2e1-m3.*(t17+L2.*t9+L3.*t10.*(1.0./2.0)).*(t16+L2.*t4.*t5+L3.*t6.*t7.*(1.0./2.0)).*1.2e1+L1.*g.*m1.*t3.*6.0;L2.*g.*m2.*t5.*6.0+L2.*g.*m3.*t5.*1.2e1+L3.*g.*m3.*t7.*6.0-L1.*L2.*m2.*t2.*t19.*6.0-L1.*L2.*m3.*t2.*t19.*1.2e1-L1.*L3.*m3.*t2.*t23.*6.0-L2.*L3.*m3.*t4.*t21.*6.0+L2.*L3.*m3.*t6.*t21.*6.0;g.*t7.*-6.0+L1.*t2.*t23.*6.0+L2.*t4.*t21.*6.0];
