function LAG_b = bvec_LAG_4_link(in1,in2,g,in4,in5)
%BVEC_LAG_4_LINK
%    LAG_B = BVEC_LAG_4_LINK(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    07-Dec-2017 19:51:44

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
L4 = in1(:,4);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
m4 = in2(:,4);
th1 = in4(:,1);
th2 = in4(:,2);
th3 = in4(:,3);
th4 = in4(:,4);
thD1 = in5(:,1);
thD2 = in5(:,2);
thD3 = in5(:,3);
thD4 = in5(:,4);
t2 = sin(th1);
t3 = thD2.^2;
t4 = th1-th2;
t5 = sin(t4);
t6 = thD3.^2;
t7 = th1-th3;
t8 = sin(t7);
t9 = sin(th2);
t10 = th2-th3;
t11 = sin(t10);
t12 = thD4.^2;
t13 = thD1.^2;
t14 = sin(th3);
t15 = th1-th4;
t16 = sin(t15);
t17 = th2-th4;
t18 = sin(t17);
t19 = th3-th4;
t20 = sin(t19);
LAG_b = [g.*m1.*t2.*-3.0-g.*m2.*t2.*6.0-g.*m3.*t2.*6.0-g.*m4.*t2.*6.0-L2.*m2.*t3.*t5.*3.0-L2.*m3.*t3.*t5.*6.0-L2.*m4.*t3.*t5.*6.0-L3.*m3.*t6.*t8.*3.0-L3.*m4.*t6.*t8.*6.0-L4.*m4.*t12.*t16.*3.0;g.*m2.*t9.*-3.0-g.*m3.*t9.*6.0-g.*m4.*t9.*6.0-L3.*m3.*t6.*t11.*3.0-L3.*m4.*t6.*t11.*6.0-L4.*m4.*t12.*t18.*3.0+L1.*t5.*t13.*(m2+m3.*2.0+m4.*2.0).*3.0;(L2.*t3.*t11+L1.*t8.*t13).*(m3.*3.0+m4.*6.0)-g.*m3.*t14.*3.0-g.*m4.*t14.*6.0-L4.*m4.*t12.*t20.*3.0;g.*sin(th4).*3.0-L2.*t3.*t18.*3.0-L3.*t6.*t20.*3.0-L1.*t13.*t16.*3.0];
