function LAG_A = Amat_LAG_1_link(L1,m1,th1)
%AMAT_LAG_1_LINK
%    LAG_A = AMAT_LAG_1_LINK(L1,M1,TH1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Dec-2017 00:34:51

LAG_A = [L1.*2.0];
