function LAG_A = Amat_LAG(in1,in2,in3)
%AMAT_LAG
%    LAG_A = AMAT_LAG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Sep-2018 01:22:29

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
th1 = in3(:,1);
th2 = in3(:,2);
th3 = in3(:,3);
t2 = th1-th2;
t3 = cos(t2);
t4 = m3.*2.0;
t5 = m2+t4;
t6 = m3.*3.0;
t7 = th1-th3;
t8 = cos(t7);
t9 = th2-th3;
t10 = cos(t9);
LAG_A = reshape([L1.*(m1+m2.*3.0+t6).*2.0,L1.*t3.*t5.*3.0,L1.*t8.*-3.0,L2.*t3.*t5.*3.0,L2.*(m2+t6).*2.0,L2.*t10.*-3.0,L3.*m3.*t8.*3.0,L3.*m3.*t10.*3.0,L3.*-2.0],[3,3]);
