function LAG_b = bvec_LAG_2_link(in1,in2,g,in4,in5)
%BVEC_LAG_2_LINK
%    LAG_B = BVEC_LAG_2_LINK(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Dec-2017 00:43:18

L1 = in1(:,1);
L2 = in1(:,2);
m1 = in2(:,1);
m2 = in2(:,2);
th1 = in4(:,1);
th2 = in4(:,2);
thD1 = in5(:,1);
thD2 = in5(:,2);
t2 = sin(th1);
t3 = th1-th2;
t4 = sin(t3);
LAG_b = [g.*m1.*t2.*-3.0-g.*m2.*t2.*6.0-L2.*m2.*t4.*thD2.^2.*3.0;g.*sin(th2).*3.0-L1.*t4.*thD1.^2.*3.0];
