function LAG_b = bvec_LAG_3_link(in1,in2,g,in4,in5)
%BVEC_LAG_3_LINK
%    LAG_B = BVEC_LAG_3_LINK(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    07-Dec-2017 19:50:52

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
th1 = in4(:,1);
th2 = in4(:,2);
th3 = in4(:,3);
thD1 = in5(:,1);
thD2 = in5(:,2);
thD3 = in5(:,3);
t2 = sin(th1);
t3 = thD2.^2;
t4 = th1-th2;
t5 = sin(t4);
t6 = sin(th2);
t7 = thD3.^2;
t8 = thD1.^2;
t9 = th1-th3;
t10 = sin(t9);
t11 = th2-th3;
t12 = sin(t11);
LAG_b = [g.*m1.*t2.*-3.0-g.*m2.*t2.*6.0-g.*m3.*t2.*6.0-L2.*m2.*t3.*t5.*3.0-L2.*m3.*t3.*t5.*6.0-L3.*m3.*t7.*t10.*3.0;g.*m2.*t6.*-3.0-g.*m3.*t6.*6.0-L3.*m3.*t7.*t12.*3.0+L1.*t5.*t8.*(m2+m3.*2.0).*3.0;g.*sin(th3).*3.0-L2.*t3.*t12.*3.0-L1.*t8.*t10.*3.0];
