function DAE_b = bvec_DAE_4bar(in1,in2,g,in4,in5)
%BVEC_DAE_4BAR
%    DAE_B = BVEC_DAE_4BAR(IN1,IN2,G,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Dec-2017 01:26:29

L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
m1 = in2(:,1);
m2 = in2(:,2);
m3 = in2(:,3);
th1 = in4(:,1);
th2 = in4(:,2);
th3 = in4(:,3);
thD1 = in5(:,1);
thD2 = in5(:,2);
thD3 = in5(:,3);
t2 = thD1.^2;
t3 = cos(th1);
t4 = sin(th1);
t5 = thD2.^2;
t6 = cos(th2);
t7 = sin(th2);
t8 = thD3.^2;
t9 = cos(th3);
t10 = sin(th3);
DAE_b = [-g.*m1;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;0.0;L1.*t2.*t3.*(-1.0./2.0);L1.*t2.*t4.*(-1.0./2.0);-L1.*t2.*t3-L2.*t5.*t6.*(1.0./2.0);-L1.*t2.*t4-L2.*t5.*t7.*(1.0./2.0);-L1.*t2.*t3-L2.*t5.*t6-L3.*t8.*t9.*(1.0./2.0);-L1.*t2.*t4-L2.*t5.*t7-L3.*t8.*t10.*(1.0./2.0);L1.*t2.*t3+L2.*t5.*t6+L3.*t8.*t9;L1.*t2.*t4+L2.*t5.*t7+L3.*t8.*t10];
